before_script:
  - which python
  - docker info

docker_build:
  stage: build
  script:
    - docker build -t intune .

docker_deploy:
  stage: deploy
  only:
    - master
  script:
    - docker stop intune
    - docker rm intune
    - docker run -d -p 8000:8000 --name intune intune
