before_script:
  - which python3
  - docker info

test:
  stage: test
  script:
    - ./test.sh
  environment: test

docker_deploy:
  stage: deploy
  only:
    - master
  script:
    - docker build -t intune .
    - docker stop intune
    - docker rm intune
    - docker run -d -p 8000:8000 --name intune intune
  environment: production
