# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intune', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='users',
            field=models.ManyToManyField(to='intune.Profile'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='intune.Profile'),
        ),
    ]
