# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intune', '0002_auto_20170531_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='users',
            field=models.ManyToManyField(blank=True, to='intune.Profile'),
        ),
    ]
