# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intune', '0003_auto_20170531_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='composition',
            name='lastEdit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
