# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intune', '0005_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
