# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intune', '0007_composition_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('bar', models.PositiveIntegerField()),
                ('comment', models.CharField(max_length=255)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intune.Profile')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intune.Composition')),
            ],
        ),
    ]
