# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intune', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='composition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='intune.Composition'),
        ),
    ]
