# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intune', '0009_notification_composition'),
        ('intune', '0008_comment'),
    ]

    operations = [
    ]
