# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intune', '0010_merge_20170608_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intune.Composition'),
        ),
    ]
