# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intune', '0013_auto_20170609_0214'),
        ('intune', '0011_auto_20170608_2303'),
    ]

    operations = [
    ]
