# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intune', '0014_merge_20170609_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
