# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intune', '0015_chatmessage_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='composition',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='intune.Composition'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
