# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intune', '0017_profile_unread_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=60)),
                ('data', models.CharField(blank=True, max_length=10000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intune.Composition')),
            ],
        ),
    ]
